name: Bot Bacteria - Codificador WEBP LSB

on: [push]

jobs:
  infectar-imagen:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    # Cambiamos la ejecución al nuevo script
    - name: Inyectar código en la imagen
      run: node encode-webp.js

    # Cambiamos el archivo que el bot debe guardar
    - name: Guardar imagen infectada (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: caballo-de-troya-webp
        path: output_infected.webp
